server:
  profiles:
    active: prod
  port: 8090
spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true
  jpa:
#    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://147.32.81.90:5432/navi
    username: riganmic
    password: Pa3ti4ka_
    driverClassName: org.postgresql.Driver
management:
  endpoints:
    web:
     exposure:
       include: "*"    
  endpoint:
    health:
      show-details: always
    
    
    
    