server:
  port: 8090
spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true
  jpa:
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
      path: /h2-console
  profiles: default
  datasource:
    url: jdbc:h2:mem:navi;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL
    username: sa
    password: sa
management:
  endpoints:
    web:
     exposure:
       include: "*"    
  endpoint:
    health:
      show-details: always
    
    
    